### PR TITLE
Display actions specific to the current line in actions list

### PR DESCRIPTION
**Pull request by expipiplus1**
It may be desirable to use a deduplicating algorithm with a better complexity

I haven't thought about this very much or used it in anger, but thought it was worth opening a PR anyway, feel free to make whatever changes would be good, like using `codeActionsRange`, and ideally making just one call to coc and dropping the deduplicating part (although I don't know if this is possible).

### CODE REVIEW

**Comment by antoinemadec** [comment]
Actions are not even a list on coc anymore, is it ?
If your hack is working fine for both line and file actions, I could merge it.

Did you notice any slowdown after that change ?

**Comment by expipiplus1** [comment]
Yeah, that's right.

I didn't notice any slowdown, but I've only. Used it in a small way.

**Comment by antoinemadec** [comment]
@expipiplus1 OK, 3 things:

1. ```uniq()``` should be used to uniquify the list, I tested it and it seems to work
2. by using both the actions of the whole buffer + actions on the current line, different actions might result in having the same name (extract method on different text zones of a python file for instance)
3. some actions don't work with the ```CocAction('doCodeAction', selectedActionInFzfMenu)``` (like extract method in a python file)

Regarding 2., we could create add 2 separated commands: **actions_whole_buffer** and **actions_current_line**.
In that case, 1. would not be needed anymore.

Regarding 3., I don't know how to fix this.
It seems to be the case on code actions using the popup window more than once (e.g.: doing ```<Plug>(coc-codeaction)``` in a python file and selecting Extract Method will open a 2nd window asking you to name the method).

**Comment by expipiplus1** [comment]
1) But doesn't `uniq` only remove adjacent duplicates? `uniq [a,b,a] = [a,b,a]`?

2) It's very convenient and IMO more intuitive to have these displayed in the same list. I'm not sure I understand the extract-method example, are you saying that there are two extract-method actions presented (one global and one local to the line) and they have the same index?

3) so there are actions which require further input from the programmer, I did not know this and it's a cool feature! It seems orthogonal to this issue though (and IMO beyond the concern of coc-fzf)

**Comment by expipiplus1** [comment]
We should also get this `'n'` option enshrined in coc.nvim (not that there's much regard for backwards compatibility there...)

**Comment by antoinemadec** [comment]
1. that is true, I supposed ```sort(uniq(foo))``` would work but its complexity would be n2*log(n).
Anyway, I doubt the list uniquifying is gonna be a limiting factor here. **Let's not care about it.**

2. please install the ```coc-python``` extension and try it to get a better understanding of the issue.
I am saying that they are 2 actions called "extract method" that apply on different lines but which names are indistinguishable.
This is an issue, we need to find a way to fix this.

A not-too-ugly way to fix this would be to add a ```[line]``` and ```[buffer]``` on the lines as a prefix or suffix.
**What do you think ?**

3. It is orthogonal to this PR indeed. I just created #76

**Comment by expipiplus1** [comment]
>     1. that is true, I suppose `sort(uniq(foo))` would work but its complexity would be n2*log(n).
>        Anyway, I doubt the list uniquifying is gonna be a limiting factor here. **Let's not care about it.**

Cool :+1: 

>     2. please install the `coc-python` extension and try it to get a better understanding of the issue.
>        I am saying that they are 2 actions called "extract method" that apply on different lines but which names are indistinguishable.
>        This is an issue, we need to find a way to fix this.

hmm, couldn't reproduce this, could you send a screenshot or minimal example?

> A not-too-ugly way to fix this would be to add a `[line]` and `[buffer]` on the lines as a prefix or suffix.
> **What do you think ?**

I suppose so, if it's a configurable feature that would be ideal. Do you know how vscode handles this? I know for actions with an associated source position it displays a little lightbulb on the text on that line.

**Comment by antoinemadec** [comment]
Superbe, you just need to add the 'buffer' and 'line' info and I will be able to merge this PR

**Comment by expipiplus1** [comment]
Done, thanks!

image

**Comment by antoinemadec** [comment]
Closed by https://github.com/antoinemadec/coc-fzf/commit/52ce401479414341c410249d33a3c4e7962ff65e , thanks a lot for taking time to create a PR :heart:

**Comment by expipiplus1** [comment]
Thanks!

**Pull request closed without merging**
