### PR TITLE
Yanks list support based on coc-yank

### PR DESCRIPTION
**Pull request by asermax**
As discussed on #14, I went ahead and gave the yanks list a try.

After delving a bit onto `coc-yank`s repo, I couldn't find any easy way to obtain the list info directly, so instead I decided to parse the file it uses internally to save the yank history. Eventually I think it would be possible to provide a `Coc` command to access any list (since there's a well defined `List` interface as far as I could see), but for the time being this was an easy and fast way to get it working.
As for the implementation itself, I based this list on how the other ones looked like (it's my first time working with vimscript), adapting it a bit to what this particular list should do.

Let me know what you think!

### CODE REVIEW

**Comment by antoinemadec** [comment]
@asermax , looks pretty good to me!

Questions:

1. Is this a standard path: ```let s:yank_file_path = $HOME . '/.config/coc/extensions/coc-yank-data/yank'```?
2. Is there a way to get this from ```coc-yank```?
3. Does ```coc-yank``` provide a way to change this path?

Thanks,
Antoine

**Comment by asermax** [comment]
Hey, thanks for the feedback!
I did some more digging, and though the extension itself doesn't seem to provide any way to obtain the final path, the folder where the `yank` file resides is provided by coc itself during the extension's initialization.
The root folder for these paths seems to be configurable through the `g:coc_data_home` variable and accessible through the [`coc#util#get_data_home`](https://github.com/neoclide/coc.nvim/blob/2bb08e43f710d80972a0a98e6607c7301cedd77e/autoload/coc/util.vim#L498) function.
I'll adapt the logic here to at least obtain that base folder path from coc and then append the rest!

**Comment by asermax** [comment]
Done! Ended up using `coc#util#extension_root` instead but the idea is pretty much the same!

**Comment by antoinemadec** [comment]
@asermax , dopeness!
We are almost there, could you please just modify the vim-doc as well (doc/coc-fzf.txt)?

Once this is done, I will push this PR.

Thanks again,
Antoine

**Comment by asermax** [comment]
Done :+1:

**Comment by antoinemadec** [comment]
OK, so here are 2 other things that need to be fixed:

1. ```coc-yank``` uses the keyword ```yank```, not ```yanks```. Please change the ```yanks.vim``` into ```yank.vim``` and change the prompt into ```Coc Yank>```
2. it seems that only the 1st element in the list is copied, even when selecting the 2nd element. Could you please fix this?

**Comment by asermax** [comment]
Will make the changes for the first point!
I'm not being able to reproduce the second issue though, when I select an item on the list it correctly injects it into the buffer and is available on the default register as well. Any other hints on how to reproduce it?

**Comment by antoinemadec** [comment]
@asermax , for 2., this is coming for this code:
```vim
let l:content = a:cmd[0]
let @" = l:content
```

To reproduce, add ```set clipboard=unnamed``` in your .vimrc

Note that ```coc-yank``` work as expected when using the ```CocList yank``` command.
Maybe we should mimic what they are doing to ```put``` the string in the file?

**Comment by asermax** [comment]
Yup, that seems to work! I'm quite new to `vimscript` so I went for what looked like the easiest solution to modify the current buffer, I didn't delve too much on the docs since it seemed to be working :sweat_smile: 
Did the changes, let me know if anything else is missing :+1:

**Comment by antoinemadec** [comment]
@asermax , no problem. This was a tricky behavior to foresee, if I didn't have the ```unnamed``` cb option in my vimrc, I would have never caught it :smile: 

Thanks for your contribution, do not hesitate to keep the PR coming if you feel like it!

Cheers,
Antoine

**Pull request merged**
