### PR TITLE
Yank extras

### PR DESCRIPTION
**Pull request by asermax**
As discussed in #36, I'm adding some extras to the yank list:
- Added char/block/line metadata into the line, including a highlight group (should I add a highlight group for the rest of the text?)
- Added support for multi selection
- Added support for preview

For the preview feature, I initially attempted to implement using the `filename:lnum` recommendation that was mentioned on the issue, but given that yank information is "old" (doesn't necesarily represent the current state of the file where it was yanked from), this got really bad results, showing incorrect lines, showing the correct line but the text had changed or not being able to find the file altogether.
Instead, I attempted to do a "custom" preview by processing the currently selected line to make it readable on the preview section. Made some small refactors to get that working but overall I think the result is good.

I still want to play a bit more with this but let me know what you think!

### CODE REVIEW

**Comment by antoinemadec** [comment]
@asermax , I just tried your code :smiley: 

I notice that the highlight was not working on the selected line.
You can fix that by using this:
```vim
syntax match CocFzf_YankType /^>\?\s*\(line\|char\|block\)/ contained containedin=CocFzf_YankHeader
```

Then regarding, the preview, I really don't see the added value of repeating the yank in the preview window.
I think if the ```filename:linenb``` is not reliable, we should just drop the preview support.
What do you think?

Finally, for the block yank, you display the newline as ```\n```, when **CocList yank** display white spaces.

Cheers,
Antoine

**Comment by asermax** [comment]
1. I don't see any difference by making that change but I'll apply it since it's probably an environment thing.
2. I was just thinking what would be the best way to add syntax highlighting (found out about `fzf` using `bat` yesterday while digging into the preview script). 
Your idea sounds good, but I'm a bit fuzzy on the details:
    - Since creating a file for each yank beforehand would probably be very expensive, we will have to do some custom command to create it on the fly before passing it into the previewer script, does that sound right?
    - In the case we want to create the file on the fly, we probably need an external script to take care of that, I don't think it can be easily done in a `sh` oneliner.
    - It seems like we have a `tempname` function in vim which returns an unused filename within a temporary folder that vim itself creates (something like `/tmp/xeurpuri23r/1`). We can use that as a base (just the folder path) and create files with the right extensions in there. If we use an external `python` script it may be easier though.

3. This one is a side effect of trying to make the preview work, without the `\n`s the custom command wouldn't work. I'll see what else can I do about it.

Thanks for the feedback! I'll keep playing with this during the weekend.

**Comment by antoinemadec** [comment]
@asermax , 

1- got it.

2-
I fixed the preview. Please look at this: https://github.com/antoinemadec/coc-fzf/commit/2d3936f5ad08faccabc1993f8a32f471fa8aa99a

You were right about the tempfile solution not scaling up nicely.
So I created a shell script instead that uses:
```bash
echo "$yank" | bat --language $filetype
```

This works very well, both highlighting and ```\n``` are handled properly.

3-
I think you are right: do not bother replacing ```\n``` with spaces, it seems impossible anyway.

Ok, so here is what's left to do:

- add a test checking that **bat** exists in the script and use **cat** instead
- cleanup the code if needed (did not see anything wrong on my end)

THanks,
Antoine

**Comment by antoinemadec** [comment]
I pushed it myself on master as I had no permission to push on your ```feat/yank-extra-info```.
It showed your name on ```tig```:
coc_fzf_yank

Unfortunately, github does not show your name/commit for some reason.
I'm really sorry about this, this was not my intention.

For what it's worth: thanks a lot for your contribution!
I really appreciate your work on this project :smiley: 

Thanks,
Antoine

**Comment by asermax** [comment]
No worries, glad you got the preview working!
I'm trying it right now and the highlighthing looks great but the text it's not respecting the newlines for some reason, I'll see if I can figure out why and let you know :+1:

**Comment by asermax** [comment]
After some testing, it seems adding the `-e` flag to `echo` when doing the initial sed fixes it:
```sh
str="$(echo -e "$1" | sed "s/^\s*\(line\|char\|block\)\s\s//g")"
```
Not sure why it worked correctly when used inline but needs the `-e` within the script though.
Do you mind testing if this works correctly in Mac as well and pushing the change in?

**Comment by antoinemadec** [comment]
@asermax , I actually use Linux (debian testing).
My script is using ```sh```, not ```bash```, some commands don't behave the same (echo -e and sed -i for instance are convinent bashisms). 

On Debian, **sh** is mapped to **dash**, which ```echo``` interprets the ```\n``` by default.
The ```-e``` option is not available.

Could you try:

1. enter the shell ```sh``` in a terminal, type ```echo "foo\nbar``` and tell me what it does?
2. give me the output of this command: ```ls -l $(which sh)```

If ```sh``` points to shells with different implementations of ```echo```, I will use ```bash``` with ```echo -e```. That  should be standard.
Please let me know!

Thanks,
Antoine

**Comment by antoinemadec** [comment]
https://docstore.mik.ua/orelly/unix/upt/ch46_10.htm

**Comment by antoinemadec** [comment]
@asermax , can you try https://github.com/antoinemadec/coc-fzf/commit/10a6cc172795d3ba6e9ccb8e1e4d4cdeee66956c and let me know if it fixes it for you?

**Comment by asermax** [comment]
Oh my bad about the OS assumption, didn't think two linuxes would have a lot of env differences. I guess most of the differences have to do with shells; I use `zsh` by default and `sh` seems to point to `bash`.
Seems like that commit fixed it btw, thanks!

**Pull request closed without merging**
